services:
- type: pserv
  name: mariadb
  plan: standard
  env: docker
  autoDeploy: false
  disk:
    name: mariadb
    mountPath: /var/lib/mariadb
    sizeGB: 10
  envVars:
  - fromGroup: mariadb

envVarGroups:
- name: mariadb
  envVars:
  - key: MARIADB_DATABASE
    value: mariadb
  - key: MARIADB_USER
    value: mariadb
  - key: MARIADB_PASSWORD
    generateValue: true
  - key: MARIADB_ROOT_PASSWORD
    generateValue: true
